
package bigws.soapserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ToDOService", targetNamespace = "http://soapserver.bigws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDOService {


    /**
     * 
     * @return
     *     returns java.util.List<bigws.soapserver.ToDO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lista", targetNamespace = "http://soapserver.bigws/", className = "bigws.soapserver.Lista")
    @ResponseWrapper(localName = "listaResponse", targetNamespace = "http://soapserver.bigws/", className = "bigws.soapserver.ListaResponse")
    public List<ToDO> lista();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "guardarCambios", targetNamespace = "http://soapserver.bigws/", className = "bigws.soapserver.GuardarCambios")
    @ResponseWrapper(localName = "guardarCambiosResponse", targetNamespace = "http://soapserver.bigws/", className = "bigws.soapserver.GuardarCambiosResponse")
    public void guardarCambios(
        @WebParam(name = "arg0", targetNamespace = "")
        List<ToDO> arg0);

}
