
package bigws.soapserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ToDOServiceService", targetNamespace = "http://soapserver.bigws/", wsdlLocation = "http://localhost:8081/ToDO?wsdl")
public class ToDOServiceService
    extends Service
{

    private final static URL TODOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TODOSERVICESERVICE_EXCEPTION;
    private final static QName TODOSERVICESERVICE_QNAME = new QName("http://soapserver.bigws/", "ToDOServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ToDO?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TODOSERVICESERVICE_WSDL_LOCATION = url;
        TODOSERVICESERVICE_EXCEPTION = e;
    }

    public ToDOServiceService() {
        super(__getWsdlLocation(), TODOSERVICESERVICE_QNAME);
    }

    public ToDOServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ToDOService
     */
    @WebEndpoint(name = "ToDOServicePort")
    public ToDOService getToDOServicePort() {
        return super.getPort(new QName("http://soapserver.bigws/", "ToDOServicePort"), ToDOService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToDOService
     */
    @WebEndpoint(name = "ToDOServicePort")
    public ToDOService getToDOServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapserver.bigws/", "ToDOServicePort"), ToDOService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TODOSERVICESERVICE_EXCEPTION!= null) {
            throw TODOSERVICESERVICE_EXCEPTION;
        }
        return TODOSERVICESERVICE_WSDL_LOCATION;
    }

}
